name: MultiCommand
main: de.homerbond005.multicommand.MultiCommand
author: HomerBond005
version: '@PROJECT_VERSION@'
commands:
    muco:
        description: Main Command.
        usage: Type /<command> help for help.
    nothingatall:
        description: Empty command
        usage: No usage.