name: MultiCommand
main: de.HomerBond005.MultiCommand.MultiCommand
author: HomerBond005
version: 1.5
commands:
    muco:
        description: Main Command.
        usage: Type /<command> help for help.