name: MultiCommand
main: de.HomerBond005.MultiCommand.MultiCommand
author: HomerBond005
version: 2.1.2
commands:
    muco:
        description: Main Command.
        usage: Type /<command> help for help.
    nothingatall:
        description: Empty command
        usage: No usage.